### ISSUE TITLE
Dotnet Core Support

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/usaddress#10]
I noticed that some of the forks out there seem to have been created just to add core support.  It would be great to roll that support into this library.

**Comment by waynebrantley** [comment]
Before I saw your project, I already converted the original source to support .net core and build on AppVeyor.  I can apply that to this project in a PR if you are interested?

**Comment by jamesrcounts** [comment]
Yes, I think we can work together on this, but I'd like to solve the broken addresses first.

**Comment by waynebrantley** [comment]
Other questions - are you licked in on the style of the code?
I am a big r# user and styles - would love to change this code up.   In fact, on what  I started above I changed it all.
Also, why the change to the 'Approvals' thing in unit testing?  Seems overkill to put the results in files instead of just in the source like it was to start with?
Also, the XUnit you are using - I cannot seem to get theory to work so I can do test cases.   
While your code has a few fixes in it - my repo above is already .net core compatible, has pretty standard coding styles and such.  Could consider just porting your changes into mine...

**Comment by jamesrcounts** [comment]
Yes, pretty much set on the style of the code.  Not sure how ReSharper plays into that since I'm using Resharper too.  Its a little bit out of line with what I would do today, but that's just because it's relatively old.

Approvals are not new.  It's been in this fork of the codebase since the beginning.  

The version of xUnit is probably in the packages.config file, so you could go look there for your answer.

You are welcome to keep your fork, and since this is GPL code you are welcome to port as much or as little of this repo into it.  Although I hope you will consider continuing to work on this codebase.

**Comment by PureKrome** [comment]
Re: .NET Core support .... is this still being held off because of wanting to fix some address in #7 that aren't parsing?

I wouldn't use that as an excuse to hold back porting to Core, IMO.

And throw in AV CI/CD (like @waynebrantley had in his fork).

Lets upgrade, move on and keep this modern.

**Comment by jamesrcounts** [comment]
@PureKrome I hadn't seen your message, and I think I agree at this point.  I'll look at this again next week.

**Comment by jamesrcounts** [comment]
[released](https://www.nuget.org/packages/AddressParser/1.0.0#) 1.0.0 as a netstandard1.4 library
