### ISSUE TITLE
Very slow!

### ISSUE THREAD

**Issue by donnyv** [jamesrcounts/usaddress#17]
I'v been using the old AddressParser library and this version is extremely slow. It also installs a ton of libraries that I'm pretty sure it doesn't need. System.Security.Cryptography??

If your going to take over this library please make sure it doesn't run slower and clean house with the libraries.

**Comment by jamesrcounts** [comment]
Thanks for your feedback.  I've been maintaining this library since 2014.  When you refer to the old version being faster are you talking about the version from CodePlex?  Or the version before we converted this library to be a netstandard 1.4 library?  

Pretty sure that the System.Security.Cryptography reference is coming from netstandard.  If you look at the csproj you'll see that this library doesn't reference any packages outside netstandard. So sorry you don't like it, but the netstandard implementation is the way things will be from now on.

**Comment by jamesrcounts** [comment]
Sorry, I think the ship has sailed when it comes to the idea of taking actions based on comparisons with the CodePlex version.  Luckily the CodePlex code is still available for download on the archived site.  You can continue to use that.

**Comment by cwilby** [comment]
You can improve the performance of this library by disabling regex compilation per [this PR](https://github.com/jamesrcounts/usaddress/pull/1).  In my own use case address parsing went from 1s/address to ms territory.

```csharp
string text = "...";
var addressParser = new AddressParser { CompileRegex = false };
return addressParser.ParseAddress(text);
```
